openapi: "3.0.0"
info:
  title: Example API
  version: "0.1.0"
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: OK
  /users:
    get:
      summary: List users
      responses:
        '200':
          description: OK
    post:
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Created
