openapi: "3.0.0"
info:
  title: Sample API
  version: "0.1.0"

paths:
  /:
    get:
      summary: Root endpoint
      responses:
        "200":
          description: OK

  /status:
    get:
      summary: Status Check
      responses:
        "200":
          description: Status OK
